# Generated by Django 2.0.2 on 2020-06-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20200524_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_CLOSED', '超时关闭'), ('PAYING', '待支付'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束'), ('WAIT_BUYER_PAY', '交易创建')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
