# Generated by Django 2.0.2 on 2020-06-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200612_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_SUCCESS', '成功'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_FINISHED', '交易结束')], default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
