# Generated by Django 2.0.2 on 2020-06-12 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200612_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 14, 27, 55, 630671), verbose_name='添加时间'),
        ),
    ]
