# Generated by Django 2.0.2 on 2020-06-12 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200612_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 22, 20, 45, 911840), verbose_name='添加时间'),
        ),
    ]
