# Generated by Django 2.0.2 on 2020-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0006_auto_20200613_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='message_type',
            field=models.IntegerField(choices=[(2, '投诉'), (3, '咨询'), (5, '求购'), (1, '留言'), (4, '售后')], default=1, help_text='留言类型：1（留言），2（投诉），3（咨询），4（售后），5（求购）', verbose_name='留言类型'),
        ),
    ]
